### ISSUE TITLE
How to apply the dataset, miniF2F to ReProver?

### ISSUE THREAD

**Issue by irene622** [lean-dojo/ReProver#23]
Hi, I read your paper, and ReProver can be experienced for miniF2F dataset.
I try to apply lean data of miniF2F, but I have few ambiguous about the experiment..

1. The lean file in miniF2F are different from your benchmark dataset.
Then, do I have to change miniF2F to the benchmark data format such as e.g, transfer to json format and {"link", "commit"...}?
If yes, what is a proper input per keys in json?

2. The experiment for miniF2F is done without retriever? or not?
For only test, applying miniF2F is runned on theorem proving without retriever??

Thank you for time!

**Comment by yangky11** [comment]
Hi,

You can use LeanDojo to extract data from miniF2F, as shown at the end of this [Jupyter notebook](https://github.com/lean-dojo/LeanDojo/blob/main/scripts/generate-benchmark-lean3.ipynb).

Then you can use [prover/evaluate.py](https://github.com/lean-dojo/ReProver/blob/main/prover/evaluate.py) to evaluate the model (trained on mathlib) on miniF2F.
