### ISSUE TITLE
[QUESTION, BUG] all theorem are discarded when using miniF2F

### ISSUE THREAD

**Issue by irene622** [lean-dojo/ReProver#26]
related issue : https://github.com/lean-dojo/ReProver/issues/23

I run the following code to evaluate the ReProver model on miniF2F dataset.
1. Extracting the datasets using the below code of [here](https://github.com/lean-dojo/LeanDojo/blob/main/scripts/generate-benchmark-lean3.ipynb)
2. Run prover/evaluate.py
    ```
    python prover/evaluate.py --data-path <path>/leandojo_minif2f/default  --ckpt_path <path>/ReProver/lightning_logs/version_232973/checkpoints/last.ckpt --split val --num-cpus 16
    ```

Then, I have results as the attached file
[mini13-238259.err.txt](https://github.com/lean-dojo/ReProver/files/12700570/mini13-238259.err.txt)

My results looks strange, 
because it print 
```
INFO     | __main__:main:166 - Evaluation done! 0 theorems proved, 0 theorems failed, 244 non-theorems     discarded
```
And results show many `EOF`warnings like
```
WARNING  | prover.proof_search:search:142 - EOF
```

Is it right result? 
What is wrong part, extracting datasets or evaluate.py? and How to fix it..?

My environment is `CONTAINER="native"` and no GPU.

**Comment by yangky11** [comment]
Hi,

It would be great if you could send me your `leandojo_minif2f` and `lightning_logs/version_232973/checkpoints`. I'll take a look and try to reproduce the problem

**Comment by irene622** [comment]
I leave the [link](https://drive.google.com/file/d/11CrCayF8x_EZFYS3EmothSp0yDAILP0E/view?usp=sharing) to download the folders `lightning_logs/version_232973`.
It is almost 1GB.

**Comment by yangky11** [comment]
I would also need the `leandojo_minif2f `

**Comment by irene622** [comment]
[leandojo_minif2f.zip](https://github.com/lean-dojo/ReProver/files/12724494/leandojo_minif2f.zip)
Oh, I miss it...
I am confused why I have `EOF` error...

**Comment by yangky11** [comment]
Just an update: I'm swamped recently and will be able to take a look next week.

**Comment by irene622** [comment]
I don't know why...
[HERE](https://drive.google.com/drive/folders/1ac2fegmJE2F3YV1lQoyXYEDKaWuaWVi4?usp=sharing) is the downloading link.
I upload again the folder instead of a zip file.

**Comment by irene622** [comment]
I think my problem is solved by using server which is available Docker.


Close the issue.
