### ISSUE TITLE
Unknown package "Mathlib"

### ISSUE THREAD

**Issue by hongjin-su** [lean-dojo/ReProver#58]
In reproducing numbers in the paper, I encounter the error `unknown package 'Mathlib'`. Do you know what is the potential issue? Thanks!

**Comment by yangky11** [comment]
It would be more helpful if you can post the exact steps to reproduce the error.

**Comment by hongjin-su** [comment]
Thanks a lot for your response! The problem is the incorrect permission of the .elan folder, which results in the installation failure of Mathlib. Thanks a lot for the great work!
