### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by Adarsh321123** [lean-dojo/ReProver#64]
What are the most recent model checkpoints for retrieving premises and generating tactics? I was using https://huggingface.co/kaiyuy/leandojo-pl-ckpts, but it seems to have been deleted from HuggingFace.

**Comment by yangky11** [comment]
We no longer need leandojo-pl-ckpts since the model checkpoints are available in Hugging Face format. If you need models in the PyTorch Lightning format, you can use the tricks [here](https://github.com/lean-dojo/ReProver/discussions/22).
